### PR TITLE
my layout + qmk pull

### PR DESCRIPTION
**Pull request by etherandrius**

### CODE REVIEW

**Comment by hnefatl** [comment]
Closed because I keep getting notifications :upside_down_face:

**Comment by etherandrius** [comment]
surprised you kept it open this long.

**Comment by hnefatl** [comment]
I actually didn't know if you had a legit pull request somewhere in there :man_shrugging:

**Comment by etherandrius** [comment]
it's kinda legit just updating my own keymap and bringing the whole thing up to date

**Pull request closed without merging**
